### PR TITLE
Basic stats code

### PR DESCRIPTION
**Pull request by Xynth22**
Adds 3 basic stats (miner/con/player kills) and infrastructure for 2 more (base kills/caps)

Tested that code was running and called to the steam server but steam was not responding to my local server so pushing for test.

### CODE REVIEW

**Comment by BackTrak** [comment]
Hi Xynth, thanks, I will push these shortly!

**Comment by BackTrak** [comment]
I found a few issues, will commit some updates shortly.

**Comment by Xynth22** [comment]
OK let me know if there is something i can do.

**Comment by BackTrak** [comment]
It's nothing major, it just needs to block until steam hits the callback to report the user stats are received. I'm almost done adding that. Do you think you could put in the ranks stuff next? I would like to launch with that! If you could make the ranks go Novice 1-7, Intermediate 1-7, Veteran 1-7 and Expert 1-7, that would be perfect.

**Pull request merged**
