### PR TITLE
Training II

### PR DESCRIPTION
**Pull request by Radulfr4**
- Major improvements for wingman AI.
- Lots of online capabilities ported to offline.
- All used in TM6/10. Also enemy waves for those and stuff.
- Minor, but important change for key setup

Looks like it doesn't interfere with old server side Phoenix faction AI to display correctly.

https://trello.com/c/IBwrBiTq/245-improve-training-ii
https://trello.com/c/waUwZkUh/244-improve-wingman-ai
https://trello.com/c/jhMoq1fd/290-esc-g-c-name-the-blocking-keybind

### CODE REVIEW

**Comment by Radulfr4** [comment]
Huh .. is this still an issue? You didn't mention it earlier.

I removed AI from CheatPlayers because the player is one in training missions. I'm sure that could be changed as well.

**Comment by Astn** [comment]
Ya, still an issue. I had to put that line back in the pigs branch until we find a way to solve it. 

Here is where my head is at right now.

* Understand the ramifications of *CheatPlayer* to determine if a person running training missions needs to be one.
* Understand the ramifications of a bot being reported as a *Wingman* to see if we could piggyback bots as *Wingman*.
* Create a new indicator based off of the player CDKey matching the Bot CDKey. 
* What are the implications of removing *CheatPlayer* from everything? What is it used for?

**Comment by Radulfr4** [comment]
The only difference CheatPlayer made in training missions was in fact that AI thing. There is no reason not to change it to a normal player as far as I can see.
It lacks a straight-forward way to do it, but surely the right solution. Will get this changed.

Outside of enabling AI, CheatPlayers can board another's ship no matter if it has turrets. They also can see factions in the teamscreen with IDs >300, but that doesn't apply to any on PCore.
So not used for much at all.

**Comment by Radulfr4** [comment]
So I'd change BaseClient::CreateDummyShip() to be created with the pilot type c_ptPlayer instead of c_ptCheatPlayer. CreateDummyShip() calls ModifyShipData() which allows pigs to be another pilot type from the start. For normal online players the dummy ship gets entirely replaced anyway.

Would that work for you?

https://github.com/Radulfr4/Allegiance/commit/6bddda9e1dd73eb46f2b065f7617f68d344742bd

**Pull request merged**
