### PR TITLE
More work to upstream

### PR DESCRIPTION
**Pull request by bog-dan-ro**
@BackTrak I actually managed to nuke all PCHs & add CMake files from all projects that Allegiance depends on. I could even build Allegiance with cmake + mingw and run it on windows. Sadly for some mysterious reason MSVC produces buggy code and Allegiance crashes at startup, so, I'll keep them in my repo until I figure out what's going on. If you want to try all the patches you can check my repo:master branch.

### CODE REVIEW

**Comment by BackTrak** [comment]
Hi Bogdan, will there be any issues building and running these commits from MSVC? I just want to be sure I don't impact Rock's work with this merge. Thanks!

**Comment by bog-dan-ro** [comment]
These are safe, they are small fixes.

**Comment by pvandommelen** [comment]
Merged. Cool!

One issue with this is that you made some changes in the steam library, may cause us problems when we want to update that.

**Comment by bog-dan-ro** [comment]
Those changes are to silent some warnings in mingw. /me doesn't like warnings :)

**Comment by bog-dan-ro** [comment]
@pvandommelen @BackTrak Folks I need help from VS experts :).
I have some problems with my latest changes on VS. Something very VERY strange is happening:
1. WinTrekClient is a global object which is created correctly only once
2. in [`Wintrek.cpp:2862 m_pClientEventSource = trekClient.GetClientEventSource();`](https://github.com/bog-dan-ro/Allegiance/blob/fix_vs/src/WinTrek/WinTrek.cpp#L2862) the pointer of trekClient  (`&trekClient`) is correct, the same as `this` in 1.
3. If I'm using the debugger and step into `WinTrekClient::GetClientEventSource()`, `this` has other (and wrong) value and it returns a `nullptr`.

I pushed this code in my repo https://github.com/bog-dan-ro/Allegiance/tree/fix_vs in **fix_vs** branch (in master I'll continue my porting).

I want to mention that, now that I have CMake scripts for all **Allegiance** projects, I could compile and run it with mingw-w64 on windows, and I didn't seen the problem that I described.

Before I'll call an exorcist to do something to my VS, I thought maybe VS experts will figure out what option I didn't set :). So, if you have a few minutes to spend, please have a look to my code.

Thanks!

**Comment by pvandommelen** [comment]
@bog-dan-ro 
Switched to your branch, exact same issue. The extern trekClient variable seems wrong sometimes (a variable where the constructor never ran). The "extern" screwing up some somehow because the files are compiled in a different order?

This is beyond me.

**Comment by BackTrak** [comment]
I have seen this behavior before when adding new virtual method signatures into header files, it seems to scramble up the memory allocations. Adding new virtual method signatures at the end of the header files does not cause the issue. I don't know why this happens with Allegiance's code base. I will check it out a bit and see if that's the cause.

**Comment by BackTrak** [comment]
It looks like the scope changed on where "GetClientEventSource()" is reading from due to the clintlib.h no longer being inside a pch. When I moved the body of GetClientEventSource() from the header and into clintlib.cpp, the issue goes away and the correct value is returned. I'm guessing that BaseClient is in the inheritance chain for TrekWindow somehow, and it's reading the local trekwindow m_pClientEventSource instead of the one in BaseClient. This is very goofy for sure!

**Comment by BackTrak** [comment]
The only solution I'm seeing so far is to remove all of the functional code from clintlib.h and put it into clintlib.cpp. I wish I could figure out a solution that was less labor intensive... but overall, it's better practice to split them up anyway. :/

**Comment by kgersen** [comment]
what the point of all this ? has this be discussed somewhere before committing this to 'master'. I'm having a hard time syncing everything with my version and for what ? 
may be commit this to a special branch ?

**Comment by BackTrak** [comment]
Hi KG, 

Bogdan is working towards getting the code base into standard C++ v14 without the windows specifics so that the code can be compiled and run on Linux. Each iteration that he completes brings us closer to this goal. 

However, this most recent change has created one weird issue. When clintlib header is moved directly into wintrek.cpp without a PCH, then inline functions in the header do not reference BaseClient members, they seem to go into arbitrary memory. Any suggestions on why that may be happening now?

**Comment by kgersen** [comment]
hum yeah that's is why I thought but it's not the proper way to do this. Actually it's the backward way to do this...
That subject is not new for me. I've thought about this for a long time now. For years.
There is no point starting to change the code like this while the Windows specifics are still here. This just add complexity to an already complex code.
There is no point to 'port' to or compile on Linux **while** the Windows specifics are still here. 
That is what I started in the 'kg-work' branch on my repo: remove the Windows specifics.
These are:
- use of the registry
- ole/com stuff (agc stuff)
- direct play
- direct3d 
- some specific win32 calls and the main Windows even loop

Once these are removed/changed then and **only then** you can start thinking about having the code compile on Linux or even Mac, about moving away from vs, etc

Otherwise you'll just add complexity and problems like the one you mention and still not moving toward removing the Windows specifics. You'll port and change code that eventually will be removed anyway...

I've already did some work on the 'kg-work' branch, the server code can run without ole/com and the regsitry. The next step is to remove DirectPlay. That would be useful and it's a mandatory step to have a Linux port so there is really no point doing anything else before that.

**Comment by BackTrak** [comment]
Those are fine points, but you could also argue the other way, that the code should be standardized to the current version of C++ and made to build on Linux so that those who would rather work on that platform (and be interested in doing the conversion work) would have an easier time. As long as BogDan has the time and willingness to do this type of updating, there's no real reason to hold back. The changes are all around data types at the moment. On the flip side, this type of refactoring always incurs risk. So far the changes have been very minimal, and Bogdan has been doing a great job of keeping the checkins small and iterative. 

It sounds like the main pain here is that you are both refactoring in the same areas which is causing you (KG) some painful merges. It feels like once this is done, this pain should subside, but I can see where it would cause some trouble.

The current issue we are seeing appears to be related to PCH, but it's a mystery to me as to why. 

@bog-dan-ro it might be easier if you roll back to the training fix, and then roll forward just the header changes in wintrek, but do not remove the PCH file so you can test changes on interval to see where this is coming from. I spent several hours on it, but couldn't see a way forward outside of moving all the functions out of clintlib.h, which looks like a pain, and I'd like to know where this behavior is coming from.

**Comment by bog-dan-ro** [comment]
@BackTrak 
> I have seen this behavior before when adding new virtual method signatures into header files ...

Strange ... usually the linker should not let you do that...

> It looks like the scope changed on where "GetClientEventSource()" is reading from due to the clintlib.h no longer being inside a pch. ....

Hmmm this means that I might forget to include something in `clintlib.h` ... I'll check that.

> The only solution I'm seeing so far is to remove all of the functional code from clintlib.h and put it into clintlib.cpp ....

I'll do that if it will make VC happy :) ... As I mentioned, compiling it with mingw-w64 just works.

> [...]  and I'd like to know where this behavior is coming from.

I'll keep these changes in my fork for the moment, until you'll figure out what's going on.

@kgersen 
> [...] has this be discussed somewhere before committing this to 'master'. 

I express my intention here https://www.freeallegiance.org/forums/index.php?showtopic=72492

> [...] may be commit this to a special branch ?

Committing it in special branch will make syncing a pain. That's why I'm creating small atomic patches which should not affect windows development for the moment.

> hum yeah that's is why I thought but it's not the proper way to do this. Actually it's the backward way to do this...

It looks like `it's not the proper way` ;-).
I choose to add CMake files & make it compile with gcc first because I wanted:
- to be able to build & run the project also from linux (using mingw cross compiler & wine) 
- to be able to use clang-tidy to modernize the code (replace NULL with nullptr, add override for virtual methods, etc.)
- to be able to add a travis script which will prevent people to break the current setup (@BackTrak BTW can you please enable [travis](https://travis-ci.org/) for this project? I'd like to create a travis/docker script next weeks).
- and last but not least to be able to use other IDEs than VS. Because none of these IDEs can't handle pch, I had to nuke pch too, otherwise I'll not be able to use these IDEs to do refactoring.

Now that I can compile the project also with mingw, I'll start axing the windows specific bits.
BTW @BackTrak is there any reason why the issues are turned off? I'd like to add these steps to issues tracker. this way we can discuss them openly and also it will be easier to monitor the progress.

> That is what I started in the 'kg-work' branch on my repo: remove the Windows specifics.

I'll check your branch soon!

**Pull request merged**
