### PR TITLE
More changes

### PR DESCRIPTION
**Pull request by bog-dan-ro**
@BackTrak now that I enabled cross-compiling from linux, can you please fix the EOLs ? (check https://help.github.com/articles/dealing-with-line-endings/ for more info).

Also it will be nice if you can remove all obsolete project and unused files/classes. It will save me some time ;-)

### CODE REVIEW

**Comment by bog-dan-ro** [comment]
All patches up to 1f4e335  (`[sound_engine] Nuke pch & compile with mingw-w64`) are atomic, e.g. you can build the entire solution if you checkout 1f4e335, sadly starting with `[engine] ... ` there are not anymore, because they are including each other, so you need to pull them all including the last one to build the entire solution.

**Comment by BackTrak** [comment]
Hi Bogdan, Do you mean that you would like to switch all CRLF to LF based on that article? Just want to make sure I'm moving it the right way. :)

**Comment by BackTrak** [comment]
Hi Bogdan, I see that you brought back some code that was previously commented out. Was this intentional? It would appear that in the pre-change code, this path would always have failed with an assert, so I'm guessing it wasn't called before? It's certainly called now, so that's got me confused. ;)

Old: 

```
case ShadeModeCopy:
                if (bClip) 
				{
					// Copy vertex, set light value to 1, 1, 1, 1.
					_ASSERT( false );
//                    m_pfnLightVertex = &Device3D::LightVertexCopy;
				} 
				else 
				{
					// No lighting or transform. Uses textured screen space coords.
//                    m_pfnLightVertex = &Device3D::TransformNoClipNoLight;
					_ASSERT( false );
                }
                break;
```

New:

```
case ShadeModeCopy:
                if (bClip) 
				{
					// Copy vertex, set light value to 1, 1, 1, 1.
//                    ZAssert( false );
                    m_pfnLightVertex = &Device3D::LightVertexCopy;
				} 
				else 
				{
					// No lighting or transform. Uses textured screen space coords.
                    m_pfnLightVertex = &Device3D::TransformNoClipNoLight;
//                    ZAssert( false );
                }
                break;

```

**Comment by BackTrak** [comment]
Hi BogDan, 

Sorry, one last request, could you also please ensure that FZRelease builds with your changes as you go? 

Thanks for doing all of these, it's looking good!

**Comment by BackTrak** [comment]
Hi BogDan, if you look at the solution config, you can skip any projects that are not set to build on release. I don't want to remove them because Imago did a lot of work with bots (pigs) in R8 that I would like to bring into R9 at some point, but they are not there right now, so any conversion work you do in those projects would most likely need to be redone when we bring in that code. 

You can skip:

Pig*
AutoUpdate
cvh
mdlc
mdledit
Reloader

Thanks!

**Comment by bog-dan-ro** [comment]
> Hi Bogdan, Do you mean that you would like to switch all CRLF to LF based on that article? Just want to make sure I'm moving it the right way. :)

They will be LF only in the git repo, then, depending on the OS, when you'll clone the repo you'l' get CRLF on windows, LF on *NIX and CR on osx. It is not high priority, we can do this step after I have all `Allegiance` projects working with CMake and when I start port it to linux.


> I see that you brought back some code that was previously commented out. Was this intentional? [...]

Ah sorry, that was not intentional :) . I just wanted to comment that strange `if` which lead to an assert no matter what ;-).

>Sorry, one last request, could you also please ensure that FZRelease builds with your changes as you go?

UPS, I'll be more careful.

> if you look at the solution config, you can skip any projects that are not set to build on release[...]

For the moment I'll focus on `Allegiance` only.


Thanks for quick reviews & merges !

**Comment by BackTrak** [comment]
Sorry for the delay, I added the .gitattributes to the project and applied the line endings to all the files. Hopefully I did that one right! :)

**Pull request merged**
