### PR TITLE
Get all of the Pig projects compiling again

### PR DESCRIPTION
**Pull request by Astn**
# Why
The 'Pig' projects are Microsoft's original tooling for testing. Then allow you to script behaviors and have those players interact with the rest of the game the same way normal players interact with it. Except instead of using the Allegiance UI client, they use PigSrv, which is an implementation of a game client the same that Allegiance is.
Additionally their scripted capability would make it easy to enable scripted opponents. For example, a Player vs Computer match similar in spirit to tower defense, or CoD Zombies survival modes. Waves of enemy get stronger and stronger and your goal is to keep your base alive. etc. 
It is my thinking that this would allow people to play when there are not enough people online to get a larger conquest type of game going.

## Current State
Ready for testing. 🐷 

## Progress / Tasks

- [x] Updated projects to target 141_xp.
- [x] Fixed some of the includes, and linker issues.
- [x] Made some adjustments to Pigsrv and zlib/tref.h to get PigSrv to compile. Reverted back to DWORD in tref.h.
- [x] Added Steam support to PigSrv
- [x] Create PigClient C# project for launching pigs.
- [x] Added script error logging
- [x] Added script loading logging
- [x] Added new functions to the pigs. (MissileRange, MissileLock, AttackStation, AttackShip)
- [x] Add CDKey to PgAccts.ini so it can be provided along with user and password. This is to enable white-listing capability.
- [x] PigSrv should pass the CDKey from PgAccts as part of the login process.
- [x] Lobby should allow pigs with correct CDKey to login.
- [x] Server should allows pigs with correct CDKey to login.
- [x] PigClient should restart PigSrv if it crashes and get the pig count back to its last state.
- [x] In aaa.pig - Add game mode (virtual for now as pigs are client side beasts) where all Pigs join the same team and do not allow humans on that team.
- [x] If aaa.pig is game owner, set the game to some nice settings and launch it.
- [ ] Don't launch the game unless there are opponents on the other team, and they are *ready*

## Release Notes

All COM objects will need to be unregistered and registered again, as there are changes.

## Concerns
 There have been some changes to the datatypes used in ZLib to support Linux. I've created some defines to put the datatype back the way there were where the change was breaking COM.

### CODE REVIEW

**Comment by kgersen** [comment]
plz keep this out of the master branch. make a special branch for instance.

Alleg code needs simplification and trimming not bringing back outdated stuff that can be done in a more modern and better way.

**Comment by Astn** [comment]
I'm with you, I'd love to simplify, trim out stuff and do things better and more modern. And I think getting the Test projects back to a compiling state will ultimately make that process safer and quicker than doing it without them.

I would prefer to make changes in an incremental way where possible and have a plan for what and how the test projects are replaced.

Is there something that you think can be done in the short term that would allow us to benefit from being able to use the test projects and also accommodate moving towards them being simpler and more modern?

**Comment by kgersen** [comment]
what the point of using the Test projects (pigs) ? they heavily use specific Windows outdated technologies like ole/com and vbscript. there is really no point resurrecting that old code. really. This adds complexity for no gain and renders even more difficult to move away from Windows.

**Comment by Astn** [comment]
> what the point of using the Test projects (pigs) ?

1. Testing. 
     > The 'Pig' projects are Microsoft's original tooling for testing. They allow you to script behaviors and have those players interact with the rest of the game the same way normal players interact with it. Except instead of using the Allegiance UI client, they use PigSrv, which is an implementation of a game client the same that Allegiance is.
2. Scripting. 
     > Additionally their scripted capability would make it easy to enable scripted opponents. For example, a Player vs Computer match similar in spirit to tower defense, or CoD Zombies survival modes. Waves of enemy get stronger and stronger and your goal is to keep your base alive. etc.
It is my thinking that this would allow people to play when there are not enough people online to get a larger conquest type of game going.



> they heavily use specific Windows outdated technologies like ole/com and vbscript.

1) VBscript. They use Windows Script Host which abstracts the script engine that is used. So we can use JScript (javascript) or any other scripting engine that has a Windows Script Host adapter.
   1) We could replace Windows Script Host with another implementation that is not windows dependent, and still use a Javascript host.
2) OLE/COM. Could potentially be replaced with PPAPI/NPAPI or some other xplat plugin api (still researching). 
   1) I *think* the COM stuff is pretty isolated to just the Pigs, so leaving it in should only mean that the Pigs must be built / run on windows. This should not prevent the Server, Lobby, or Allegiance client from building and running on linux / mac.

It sounds like we plan to remove *COM* and *Windows Script Host*, basically keeping PigSrv and replacing the rest. Does that address your concerns? Or what approach would you take?

**Comment by BackTrak** [comment]
I see no reason not to merge this into master. I understand the desire to give things a scrub, chop unnecessary code, update away from com, etc. But, if no one is available to do the work now, then it's a moot point. It is better to have working old code, even if it's not the greatest. We can at least get the features out of this existing code which could enable simple things like bot practice matches now. And really, all we're doing is  adding pig projects back to the solution. 
YP , if you have the time to work on this, then please work on the area you're interested in. Let me know if you want to add a bot service to one of the alleg servers, if be happy to help set that up. 

One request tho, in zlib, could you put bogdan's type changes, and then add yours with compiler switches? I'd like to avoid flip flopping between your two efforts. Hopefully zlib is the only conflict point.

Thanks!

**Comment by Astn** [comment]
> Let me know if you want to add a bot service to one of the alleg servers, if be happy to help set that up.

I'd love to, and any help you can give is welcome. The biggest hurdle I see (outside of get pigs working again) is creating steam accounts for the bots, or something that allows the bots to present them selves to the server such that they are still a *player*.

> One request tho, in zlib, could you put bogdan's type changes, and then add yours with compiler switches? 

Great idea, I'd be happy to.

**Comment by kgersen** [comment]
@YP: I know what Pigs are and how they work(ed), I used them a lot back then.

Pigs are not designed to add bots practice or whatnot. This is a very wrong way to use them because changes to them will impact the game client too since their share the ClintLib with it. (plus there a tons of potential security & cheat issues with them not to mention other technical stuff you'll discover yourself when you really use them other than for a just a minute  for fun). On top of that each pig consumes a DirectPlay network connection to the server and we all know the issues with DirectPlay.

So the plan ,at least mine, I dunno if there is an official plan which is may be the root of our difference,  was simple:
- scrub/trim the code to keep the minimum required to run a lobby , servers and clients. I've started this in my branch, I have a fully working server which doesn't use AGC, doesn't require OLE/COM registration and doesn't use the Windows Registry. It's a fully autonomous executable that only required an artwork folder and some parameters passed thru cmd line or a config file. Next step  was to scrub the lobby in the same way then the client (mainly the registry). That's when I got ill and stopped contributing (see https://github.com/kgersen/Allegiance/projects/1 )
- next step was to rework the IGC part to split it a bit so I could integrate more easily ICE and AME.
- then add a scripting engine directly to IGC to extend the 'drone' feature (miners, cons) with more custom code. Define a GOM (Game Object Model) that exposes IGC in JS similar to a DOM in a browser.
- then bundle Chromium into the game engine and complexly remove the UI old code and replace it with HTML/JS code (the 3D view is kept and rendered into a DOM canvas on top of which DOM UI elements are drawn with HTML/JS and the JS code can interact with the GOM to read/write data).
- then replace DirectPlay with some websocket code
- then replace Direct3D with web-gl
- then we see the plan...evolve from current code to a full 'in browser' game using webgl/html/js.
why ? because there are tons and tons of people that know html/js and there are tons of existing code in JS to do whatever we want.

I see the community has taken a completely different approach by going the LUA route which is imho an outdated route. Few people know lua compared to the millions who know JS (or langages that transpile to JS like TypeScript,  Coffee, Dart, etc). Likewise by trying to revive Pigs.

**Comment by yp** [comment]
@kgersen, maybe you mentioned the wrong person...

**Comment by pvandommelen** [comment]
I would prefer practice matches to be implemented in some other way (server game mode). But if this works well I don't see a reason not to try it.

derail:
@kgersen 

Is it possible for some of those changes to be merged? It seems that you have several long living impactful branches which makes it hard to collaborate. If your server changes are done, I don't see any reason to keep that in a separate branch until the entire migration is complete.

I have considered chromium as a new UI system. It would have been a huge amount of work to integrate into the current engine. With Chromium being asynchronous by default there would be no guarantee that the final system would be well suited to a real time game. 

The pick for Lua as a scripting language instead of anything else is another discussion. While I've come to dislike Lua as a language I don't think there would have been any other scripting language that would have been as easily integrated.

**Comment by kgersen** [comment]
@pvandommelen
Since my changes removed completely ole/com & the registry this might broke current Steam integration and other stuff like game stats retrieval and whatnot. Check with BT if com/ole (agc and/or allsrv com automation) and the registry are used server side.
 
Why real time gaming with Chromium would be a problem ?  check http://hexgl.bkcore.com/play/ for instance.
There is also a big project called Age of Ascent using only web techs that is under dev (but kinda quiet lately...).
There was Urban Galaxy Online too but it seems they never went past the beta and closed the site (you can still find videos on YT).

**Comment by pvandommelen** [comment]
@kgersen 
The CEF which is generally used to implement chromium is intended to be used as a separate process and rendered frames have to be send between the original game process and the chromium process. Googling shows several people running into problems making this communication fast enough (such as the discussion on https://coherent-labs.com/what-developers-should-consider-when-using-chromium-embedded-framework-cef-in-their-games/). Many ui changes we would like to make would be affected by this performance/latency hit, until a full port was complete. Maybe we would be able to solve the issues, but I don't think that's a certainty. 

The UI system I'm working on is allowing us to update the game incrementally. Playing with the changes I and others are making soon after making them is amazing.

**Comment by BackTrak** [comment]
@kgersen the steam integration has no interaction with AGC or com/ole components. Data collection for stats is done from within wintrek / clintlib directly, with a stats object connected to the player object without using any event listeners. We can drop AGC without any impact to steam. The only OLE/COM that is currently in action is for AllSrvUI which is enabling the server to run in LAN mode which I resurrected to help devs get up and running with less friction. It would be nice to preserve this, maybe just with Debug compiler switches, other than that, whack away! :)

**Comment by Astn** [comment]
I had been hoping that it would be easy to just start the pigsrv and tweak a few scripts to get something basic up and running that would allow some PvE. And I ran into a wall with the pigs needing Steam Accounts. I agree with KGJV that doing the scripting from allsrv and integrating with IGC is the better approach. 

I'm going to let this pigs branch sit and chill, I'll close the pull request.

**Comment by BackTrak** [comment]
Hi Astn, I'd like to take a look at this, but I may not get time until Thursday. There's two paths we can take; I can modify the auth to bypass steam when it sees bot login credentials, or we can dig into the steam API to see how to get bot accounts working. The part of the API I was thinking of appears to be deprecated, but it's not obvious what replaced it yet (still looking): https://partner.steamgames.com/doc/api/ISteamGameServer#CreateUnauthenticatedUserConnection

I don't want to give up on this, I know you guys had it working on AZ, and I think it would be a fun feature to add, and it would give the new players something to do when nothing else is going on. The other big plus to this is that it's probably very close to working right now, as opposed to new development which is weeks/months away.

**Comment by Astn** [comment]
At this point Pigs are "playable".

Run a local lobby and server.
Join the game yourself as commander. Set to brawl with no developments.
Start PigClient (new project in the solution) 
    Hit connect. Then *create pig* a few times use the `aaa` script.
Launch the game when they have joined.

#### Troubleshooting

If you get no pig. 
- Make sure you have UnRegisted and then Registered all of the COM objects.
- Make sure PigSrv has the correct registry settings.
- Check the **log** tab for errors. 
- Make sure there is a `scripts` directory with aaa.pig and the appropriate includes at the path specified in the log.

My registry settings for PigSrv to run local.
image

What I'm using to UnRegister and Register my COM stuff. The steam_api.dll copy stuff might not be needed anymore. I think it was added as post build steps.
```
cd .\objsv141_xp\FZDebug
cp ..\..\src\Lib\steam\steam_api.dll .\agc
regsvr32 .\AGC\AGC.dll /u
regsvr32 .\AGC\AGC.dll

cp ..\..\src\Lib\steam\steam_api.dll .\test\TCObj
regsvr32 .\Test\TCObj\TCObj.dll /u
regsvr32 .\Test\TCObj\TCObj.dll

cp ..\..\src\Lib\steam\steam_api.dll .\Pigs\PigsLib
regsvr32 .\Pigs\PigsLib\PigsLib.dll /u
regsvr32 .\Pigs\PigsLib\PigsLib.dll

cp ..\..\src\Lib\steam\steam_api.dll .\Pigs\PigAccts
.\Pigs\PigAccts\PigAccts.exe -UnRegServer
.\Pigs\PigAccts\PigAccts.exe -RegServer  [USER] [PASS]

cp ..\..\src\Lib\steam\steam_api.dll .\Pigs\PigSrv
.\Pigs\PigSrv\PigSrv.exe -UnRegServer
.\Pigs\PigSrv\PigSrv.exe -RegServer  [USER] [PASS]

cp ..\..\src\Lib\steam\steam_api.dll .\Pigs\PigSrv
cp ..\..\src\Lib\steam\steam_api.dll .\FedSrv
```

**Comment by Astn** [comment]
Also some applicable conversation in #66 would it be better to continue it over here?

**Comment by LordBlacksun** [comment]
Love what you are doing! Thanks! @Astn  :)

**Comment by Astn** [comment]
This is ready for testing, and code review.

You should be able to create a single pig [aaa.pig] using PigClient from src\pigs\pigclient. From there the minPigs and Min/Max ratios should automatically add pigs and remove them to keep the game interesting.

If a pig joins a team as is made game owner because both teams were empty, it will configure the game settings and launch the game when there is an opponent.

Note, you will want to copy pigAccts.ini from scr\pigs\pigAccts\pigAccts.ini to your pigAccts output directory as that is not yet done automatically, IIRC. Also see above conversations for additional setup guidance.
  
  
allegiance 2018-01-07 03-44-07-75

image

[Vid1](https://youtu.be/0HG1932ZQXc)

[Vid2](https://youtu.be/1SMcQa8yK64)

**Comment by pvandommelen** [comment]
I noticed it's running live now. This is amazing.
Couple of things I noticed:
- it says it would wait until team ready, it launches after a few seconds anyway, even with afk set
- I'm totally outnumbered. ok for me, but maybe less great for new players. Maybe reduce their skill level even more for the first "wave"?
- Bomber is a nice addition. It can be the very first ship that launches though, which is a bit strange for newer players.
- They are doing podkilling, they probably shouldn't.

**Comment by Astn** [comment]
> it says it would wait until team ready, it launches after a few seconds anyway, even with afk set

ya, I'm not sure what to do on this one. I don't want a new player to have to click the afk button for it to be able to launch, or for someone to idle and prevent the game from running. Any ideas here?

> I'm totally outnumbered. ok for me, but maybe less great for new players. Maybe reduce their skill level even more for the first "wave"?

This is a configuration we have, right now its set to be a minimum number of bots, and then uses a  multiplier to add and remove bots to try to keep the game interesting. Maybe we could do something smarter with player ranks, or dynamic based off of how frequently bots vs players are dying. Do you have ideas here?

> Bomber is a nice addition. It can be the very first ship that launches though, which is a bit strange for newer players.

What would you feel is more normal? Don't launch a bomber in the first X minutes?

> They are doing podkilling, they probably shouldn't.

They are supposed to ignore pods, but right now they only check to change targets every 2 seconds. So if they pod you at the beginning of 2 seconds, then they have a full 2 seconds to kill your pod. We could reduce this to every second, or possibly even lower as long as it doesn't cause other problems.

**Comment by lanslans** [comment]
> ya, I'm not sure what to do on this one. I don't want a new player to have to click the afk button for it to be able to launch, or for someone to idle and prevent the game from running. Any ideas here?

Give a countdown in the chat before the game start sequence goes. Maybe 15s?

> This is a configuration we have, right now its set to be a minimum number of bots, and then uses a multiplier to add and remove bots to try to keep the game interesting. Maybe we could do something smarter with player ranks, or dynamic based off of how frequently bots vs players are dying. Do you have ideas here?

First wave 1 bot, second 2, etc... until you have I guess 6 or so, then you can scale numbers and difficulty some other way.

> What would you feel is more normal? Don't launch a bomber in the first X minutes?

Yes. Maybe 5 minutes w/o a bomber?

> Podkilling

This is actually advantageous for new players. Eliminate dead time, get them back up and rolling again.

**Comment by BackTrak** [comment]
All current work in pigwork is now in the mainline branch.

**Comment by Hshamashash** [comment]
> I noticed it's running live now. This is amazing.
> Couple of things I noticed:
> - it says it would wait until team ready, it launches after a few seconds anyway, even with afk set
> - I'm totally outnumbered. ok for me, but maybe less great for new players. Maybe reduce their skill level even more for the first "wave"?
> - Bomber is a nice addition. It can be the very first ship that launches though, which is a bit strange for newer players.
> - They are doing podkilling, they probably shouldn't.
> 

e20f098927fdc804fc03d61a8fba6a7c5821b365

**Pull request merged**
